# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c5ca11d998c4439a38187817aa3a9e0004ef17a65a76c052703fe215be1b40346ca73543c908b4b9a6c95305961362afbbc48bac9dbdd687f6ba50242efa42

test:
  secret_key_base: 04b2347cda3c862f970356b2122def165217eac57734718ff1f4c5a8a29604e43e4adf4c34975e1a985a171f018c488e887a0bd00ee5efb6aa0d10654a84c877

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
